name: log_location
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  stacked: ^1.6.1+1
  stacked_hooks: ^0.1.2
  stacked_services: ^0.4.4+3
  auto_route: ^0.6.1
  get_it: ^4.0.2
  injectable: ^0.4.0+1
  flutter_hooks: ^0.9.0
  observable_ish: ^2.1.4
  hive: ^1.4.1+1
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  location: ^3.0.2
  google_maps_flutter: ^0.5.28+1
  intl: ^0.16.1

dev_dependencies:
  build_runner: ^1.10.0
  injectable_generator: ^0.4.1
  auto_route_generator: ^0.6.0

flutter:
  uses-material-design: true
